// ── Mock Customers ──────────────────────────────────────────────────
export const MOCK_CUSTOMERS = [
  {
    id: 'cust-001',
    name: 'Arun Kumar',
    email: 'arun@example.com',
    phone: '+91 98765 43210',
    address: '12, Anna Nagar, Chennai',
    company: 'AK Prints',
    notes: 'Regular customer, prefers matte finish',
    createdAt: '2026-01-15',
    active: true,
  },
  {
    id: 'cust-002',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 87654 32109',
    address: '45, MG Road, Bangalore',
    company: 'Priya Designs',
    notes: 'Always needs rush delivery',
    createdAt: '2026-02-20',
    active: true,
  },
  {
    id: 'cust-003',
    name: 'Ravi Patel',
    email: 'ravi@example.com',
    phone: '+91 76543 21098',
    address: '78, Jubilee Hills, Hyderabad',
    company: 'Patel Enterprises',
    notes: '',
    createdAt: '2026-03-10',
    active: true,
  },
  {
    id: 'cust-004',
    name: 'Deepa Menon',
    email: 'deepa@example.com',
    phone: '+91 65432 10987',
    address: '23, Marine Drive, Kochi',
    company: 'Deepa Events',
    notes: 'Corporate events specialist',
    createdAt: '2026-04-05',
    active: true,
  },
  {
    id: 'cust-005',
    name: 'Karthik Raj',
    email: 'karthik@example.com',
    phone: '+91 54321 09876',
    address: '56, T Nagar, Chennai',
    company: 'KR Marketing',
    notes: 'Bulk orders only',
    createdAt: '2026-05-18',
    active: false,
  },
  {
    id: 'cust-006',
    name: 'Meena Sundaram',
    email: 'meena@example.com',
    phone: '+91 43210 98765',
    address: '90, Koramangala, Bangalore',
    company: 'MS Studios',
    notes: 'Prefers glossy finish for banners',
    createdAt: '2026-06-01',
    active: true,
  },
]

// ── Mock Bills ──────────────────────────────────────────────────────
export const MOCK_BILLS = [
  {
    id: 'bill-001',
    billNumber: 'INV-2026-000001',
    customerId: 'cust-001',
    customerName: 'Arun Kumar',
    stage: 'First process',
    paymentStatus: 'payed',
    priority: 'medium',
    items: [
      { name: 'Banner Printing (6x3 ft)', qty: 5, price: 1200, total: 6000 },
      { name: 'Sticker Printing (A4)', qty: 200, price: 15, total: 3000 },
    ],
    totalAmount: 9000,
    notes: 'Urgent delivery needed before event',
    createdAt: '2026-06-10',
    deliveryDate: '2026-06-15',
  },
  {
    id: 'bill-002',
    billNumber: 'INV-2026-000002',
    customerId: 'cust-002',
    customerName: 'Priya Sharma',
    stage: 'Second process',
    paymentStatus: 'non payed',
    priority: 'high',
    items: [
      { name: 'T-Shirt Printing (Custom)', qty: 50, price: 350, total: 17500 },
      { name: 'Business Cards (Premium)', qty: 500, price: 5, total: 2500 },
    ],
    totalAmount: 20000,
    notes: 'Customer wants preview before printing',
    createdAt: '2026-06-18',
    deliveryDate: '2026-06-25',
  },
  {
    id: 'bill-003',
    billNumber: 'INV-2026-000003',
    customerId: 'cust-003',
    customerName: 'Ravi Patel',
    stage: 'Third process',
    paymentStatus: 'payed',
    priority: 'medium',
    items: [
      { name: 'Flex Printing (10x5 ft)', qty: 3, price: 3500, total: 10500 },
    ],
    totalAmount: 10500,
    notes: '',
    createdAt: '2026-06-20',
    deliveryDate: '2026-06-28',
  },
  {
    id: 'bill-004',
    billNumber: 'INV-2026-000004',
    customerId: 'cust-001',
    customerName: 'Arun Kumar',
    stage: 'Packaging',
    paymentStatus: 'non payed',
    priority: 'low',
    items: [
      { name: 'Visiting Cards (Standard)', qty: 1000, price: 3, total: 3000 },
      { name: 'Letterhead Printing', qty: 500, price: 8, total: 4000 },
      { name: 'Envelope Printing', qty: 500, price: 6, total: 3000 },
    ],
    totalAmount: 10000,
    notes: 'Design to be finalized',
    createdAt: '2026-06-25',
    deliveryDate: '2026-07-05',
  },
  {
    id: 'bill-005',
    billNumber: 'INV-2026-000005',
    customerId: 'cust-004',
    customerName: 'Deepa Menon',
    stage: 'ready to delivery',
    paymentStatus: 'payed',
    priority: 'urgent',
    items: [
      { name: 'Stage Banner (20x10 ft)', qty: 1, price: 15000, total: 15000 },
      { name: 'Standee (6x3 ft)', qty: 4, price: 2000, total: 8000 },
      { name: 'Brochure (A5, Full Color)', qty: 300, price: 20, total: 6000 },
    ],
    totalAmount: 29000,
    notes: 'Event on June 30 - RUSH ORDER',
    createdAt: '2026-06-22',
    deliveryDate: '2026-06-29',
  },
  {
    id: 'bill-006',
    billNumber: 'INV-2026-000006',
    customerId: 'cust-006',
    customerName: 'Meena Sundaram',
    stage: 'First process',
    paymentStatus: 'non payed',
    priority: 'medium',
    items: [
      { name: 'Photo Album (Custom)', qty: 2, price: 5000, total: 10000 },
    ],
    totalAmount: 10000,
    notes: 'Wedding album, premium quality',
    createdAt: '2026-06-26',
    deliveryDate: '2026-07-10',
  },
  {
    id: 'bill-007',
    billNumber: 'INV-2026-000007',
    customerId: 'cust-002',
    customerName: 'Priya Sharma',
    stage: 'ready to delivery',
    paymentStatus: 'payed',
    priority: 'low',
    items: [
      { name: 'Poster Printing (A2)', qty: 20, price: 150, total: 3000 },
    ],
    totalAmount: 3000,
    notes: '',
    createdAt: '2026-06-12',
    deliveryDate: '2026-06-20',
  },
  {
    id: 'bill-008',
    billNumber: 'INV-2026-000008',
    customerId: 'cust-005',
    customerName: 'Karthik Raj',
    stage: 'Second process',
    paymentStatus: 'payed',
    priority: 'medium',
    items: [
      { name: 'Pamphlet Printing (A5)', qty: 5000, price: 2, total: 10000 },
      { name: 'Banner Printing (4x2 ft)', qty: 10, price: 800, total: 8000 },
    ],
    totalAmount: 18000,
    notes: 'Bulk order with discount applied',
    createdAt: '2026-05-28',
    deliveryDate: '2026-06-05',
  },
]

// ── Mock Activity Logs ──────────────────────────────────────────────
export const MOCK_ACTIVITY = [
  { id: 1, type: 'Bill Created', message: 'INV-2026-000008 created for Karthik Raj', time: '2 hours ago' },
  { id: 2, type: 'Status Changed', message: 'INV-2026-000005 moved to Ready for Delivery', time: '3 hours ago' },
  { id: 3, type: 'Customer Created', message: 'Meena Sundaram added as new customer', time: '5 hours ago' },
  { id: 4, type: 'Reminder Sent', message: 'Payment reminder sent to Priya Sharma', time: '1 day ago' },
  { id: 5, type: 'Bill Completed', message: 'INV-2026-000001 marked as completed', time: '1 day ago' },
  { id: 6, type: 'Invoice Generated', message: 'PDF invoice generated for INV-2026-000007', time: '2 days ago' },
  { id: 7, type: 'Status Changed', message: 'INV-2026-000003 moved to Quality Check', time: '2 days ago' },
  { id: 8, type: 'Bill Updated', message: 'INV-2026-000002 items updated', time: '3 days ago' },
]

// ── Mock Notifications (for Customer) ───────────────────────────────
export const MOCK_NOTIFICATIONS = [
  { id: 1, title: 'Order Update', message: 'Your order INV-2026-000002 is now In Progress', time: '2 hours ago', read: false },
  { id: 2, title: 'New Bill', message: 'A new bill INV-2026-000004 has been created', time: '1 day ago', read: false },
  { id: 3, title: 'Invoice Ready', message: 'Invoice for INV-2026-000001 is ready to download', time: '2 days ago', read: true },
  { id: 4, title: 'Order Completed', message: 'Your order INV-2026-000001 is completed', time: '3 days ago', read: true },
]

// ── Monthly Revenue Data (for Reports) ──────────────────────────────
export const MOCK_REVENUE = [
  { month: 'Jan', revenue: 45000, bills: 12 },
  { month: 'Feb', revenue: 62000, bills: 18 },
  { month: 'Mar', revenue: 38000, bills: 10 },
  { month: 'Apr', revenue: 71000, bills: 22 },
  { month: 'May', revenue: 55000, bills: 15 },
  { month: 'Jun', revenue: 89500, bills: 24 },
]
